// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1685726595);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1685726750);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1685726417);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1685726295);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1685726392);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{18c7465a-0632-46fe-931b-91849ea4821d}");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1685726274);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8243d07f-0976-4182-b3cd-3ac5cae58d92}");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230505052953");
user_pref("browser.startup.homepage_override.mstone", "102.11.0");
user_pref("browser.startup.lastColdStartupCheck", 1685726547);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1685726680811");
user_pref("distribution.iniFile.exists.appversion", "102.11.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1685726261);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230505052953");
user_pref("extensions.lastAppVersion", "102.11.0");
user_pref("extensions.lastPlatformVersion", "102.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"4de1e503-02a7-47e1-9674-e4dfe9fbb98c\",\"formautofill@mozilla.org\":\"a758d458-5fb0-4d43-a1d7-25ca21da6879\",\"pictureinpicture@mozilla.org\":\"9b49be39-6399-4b32-ace5-2edd0c3f3a57\",\"screenshots@mozilla.org\":\"0bebde7c-687d-4b87-9056-6c58cc06e00f\",\"webcompat-reporter@mozilla.org\":\"9484717d-4e64-41a9-9802-0c0ccc2a528d\",\"webcompat@mozilla.org\":\"33eabe30-0be7-4edf-9ebe-86e4aa78c30a\",\"default-theme@mozilla.org\":\"726331b1-8c94-460f-8617-cb81de9e2048\",\"addons-search-detection@mozilla.com\":\"5be71aee-7b6c-4328-b89e-7c03c4ebaf8b\",\"google@search.mozilla.org\":\"1472c62a-2713-4b00-81c3-73feb0e5ee84\",\"amazondotcom@search.mozilla.org\":\"df6af517-8abb-4158-8f36-4e088f503704\",\"wikipedia@search.mozilla.org\":\"aacacbcc-b959-4985-8b95-1f0860839fd1\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "f3025e9d-42ef-44a3-aee2-6977e996d98a");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1685726150);
user_pref("toolkit.telemetry.cachedClientID", "8103f7c6-87fe-4dc9-9d90-cca448566d00");
user_pref("toolkit.telemetry.previousBuildID", "20230505052953");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
